//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordCards.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordCards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 abacus	ˋæbəkəs	Sound\A\abacus.mp3	&lt;aba-=abax-:一種計算工具&gt;+&lt;-us: calculus 小圓石&gt;	一種利用小圓石幫助計算的工具	補充4
        ///abandon	əˋbændən	Sound\A\abandon.mp3	&lt;ab-:away&gt;+&lt;-band:bind綁&gt;	ban 禁令	把自己都放棄掉
        ///abase	əˋbes	Sound\A\abase.mp3	&lt;base:基礎&gt;		
        ///abate	əˋbet	Sound\A\abate.mp3	&lt;bat:打擊&gt;		
        ///abbreviate	əˋbrivɪ͵et	Sound\A\abbreviate.mp3	&lt;-brev:brief&gt;		
        ///abdicate	ˋæbdə͵ket	Sound\A\abdicate.mp3	&lt;ab-:away&gt;+&lt;-dic:say&gt;	放棄說話的權利	dictator 獨裁者
        ///abdomen	ˋæbdəmən	Sound\A\abdomen.mp3	&lt;dome 圓頂&gt;		
        ///abduct	æbˋdʌkt	Sound\A\abduct.mp3	&lt;ab-:away&gt;+&lt;-duct:lead&gt;		 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string WordCards {
            get {
                return ResourceManager.GetString("WordCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap WordCards_Icon {
            get {
                object obj = ResourceManager.GetObject("WordCards_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap WordCards_Logo {
            get {
                object obj = ResourceManager.GetObject("WordCards_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon WordCards1 {
            get {
                object obj = ResourceManager.GetObject("WordCards1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
